### ISSUE TITLE
Deprecated API authentication via URL query

### ISSUE THREAD

**Issue by ash0x0** [Xotl/cool-github-releases#13]
Using the current version of this action in `download` mode is deprecated for personal access token authorization, this is in the case of downloading assets from another repository or in general replacing the scoped `github.token` with a personal access token.
The following email is delivered to the associated account when the request is made:

```
[GitHub API] Deprecation notice for authentication via URL query parameters

On *** at *** (UTC) your personal access token (***) using node-fetch/1.0 (+https://github.com/bitinn/node-fetch) was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/***/releases/assets/***

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

This is due to the use of `node-fetch` call in [these lines](https://github.com/Xotl/cool-github-releases/blob/23160843b1013ff888a5d4a615068b23f35b1067/src/download.js#L31-L34).

I believe the workaround is simple enough and will fork, test and PR once I arrive at a fix. Making sure this issues is tracked here including all work that may currently be going into a solution.

**Comment by Xotl** [comment]
Hi @ash0x0, thanks a lot for your contribution. 😄 

I will take a look at your PR later this day.

**Comment by Xotl** [comment]
PR #14 got merged! 🥳

**Comment by Xotl** [comment]
Reopening the issue because [it will not deploy](https://github.com/Xotl/cool-github-releases/actions/runs/612558142) the latest version until i [upgrade the @actions/core package](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

I will try to fix it once i got some spare time.

**Comment by Xotl** [comment]
Dependencies got updated, now closing.
