### ISSUE TITLE
Need a way to update existing assets

### ISSUE THREAD

**Issue by brunchboy** [Xotl/cool-github-releases#6]
This action is fantastic, it may revolutionize my ability to give users access to pre-release versions of my software, building assets and attaching them to the relevant pre-release on GitHub, as well as passing assets from one job to another (for example to build installers for different platforms).

However, I need a way for the update action to replace an asset if it already exists, because for every push the pre-release build assets need to be replaced by new versions. Is this possible to add? Right now the action fails when it finds the asset already there. That is a reasonable default for most use cases, but I need a way to override it for mine.

**Comment by Xotl** [comment]
First of all, thanks for taking the time to create the issue and for using my action, is great to hear that it's useful for other people too. 😊 

I currently use my action for other projects and i didn't have that need, so i didn't add it. But i think i can start working on that feature this weekend, since it looks like a basic feature that my action must have.

I'll keep you posted on the progress. 😄

**Comment by brunchboy** [comment]
Awesome! There is no rush for this, what I have done for now is to use another instance of your action to delete the snapshot release, and then immediately re-create it to upload the new artifacts. But this causes a lot of noise for people who have subscribed to my repository about “new” releases, when the information they are interested in is already in the commit messages, and it is not really a new release. So if and when you do have the chance to add this, we’ll definitely appreciate it. But already you have enabled me to do much more.

**Comment by Xotl** [comment]
Got it... i will have some free time this weekend so i think i can give it a try and start working on improving the update mode.

Anyway, if you like the action please hit [the ⭐️star button in the marketplace](https://github.com/marketplace/actions/cool-gh-releases). 😃

**Comment by brunchboy** [comment]
Done! I didn’t even notice that before. And this afternoon I got a message from one of my users asking if I was aware of all the email the bot was generating. I explained the situation to him.

**Comment by Xotl** [comment]
It's ready @brunchboy! 😄 🎉

**Comment by brunchboy** [comment]
Sweet, I will give it a try! Thanks for getting to that so quickly.

**Comment by Xotl** [comment]
Now should replace the assets if they already exists, here's the link to the docs:
https://github.com/marketplace/actions/cool-gh-releases#mode-update-since-v107

**Comment by brunchboy** [comment]
It is working just as I hoped, with nice messages about what it is doing. So are you in Guadalajara? It’s been a long time since I was there (we visited sometimes when I lived in Mexico City as a child), but I imagine the weather is a lot nicer than it is in Madison today!

**Comment by Xotl** [comment]
Great to hear that is working as expected! 🎉 

Yes i live in Guadalajara and the weather here almost never goes below 10°C (50°F). Guadalajara has a very stable weather, that's something that i appreciate of living here. 😄 

Google says it's snowing in Madison, something that will be extremely rare here.

**Comment by brunchboy** [comment]
Yes, horrible weather arrived here this weekend. Thanks again for your nice action, and for adding my requested feature so quickly. One thing I really enjoy about open-source work is being able to collaborate with people all over the world, and you are the first developer from Mexico I’ve encountered.

**Comment by Xotl** [comment]
Yeah, it's rare to see mexican developers on open-source projects, i wonder why. 🤔
